import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { supabase } from "../lib/supabase";
import { computeBusinessChecklist } from "../lib/onboardingChecklist";
import type { Profile, Publisher, PublisherRequest, ChannelRequest } from "../lib/types";
import Button from "./Button";

function greeting(): string {
  const h = new Date().getHours();
  if (h < 12) return "Good morning";
  if (h < 18) return "Good afternoon";
  return "Good evening";
}

interface RecentView {
  publisher_id: string;
  name: string;
  created_at: string;
}

interface SearchMatch {
  id: string;
  title: string;
  body: string;
}

// All the "new" data this panel needs, self-contained — requests/
// channelRequests are the two things Dashboard.tsx already fetches, so
// they come in as props instead of being queried a second time here.
export default function BusinessHomeSummary({
  profile, requests, channelRequests,
}: {
  profile: Profile | null;
  requests: PublisherRequest[];
  channelRequests: ChannelRequest[];
}) {
  const [availableThisWeek, setAvailableThisWeek] = useState<number | null>(null);
  const [savedCount, setSavedCount] = useState(0);
  const [recommended, setRecommended] = useState<Publisher[]>([]);
  const [searchMatches, setSearchMatches] = useState<SearchMatch[]>([]);
  const [recentViews, setRecentViews] = useState<RecentView[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!profile) return;
    let cancelled = false;

    async function load() {
      // ── Saved publishers available this week ──────────────────────
      const { data: lists } = await supabase.from("saved_lists").select("publisher_ids").eq("business_id", profile!.id);
      const savedIds = Array.from(new Set((lists ?? []).flatMap((l) => l.publisher_ids as string[])));

      if (savedIds.length > 0) {
        const today = new Date();
        const weekOut = new Date(today.getTime() + 7 * 24 * 60 * 60 * 1000);
        const { data: blocked } = await supabase
          .from("publisher_blocked_dates")
          .select("publisher_id")
          .in("publisher_id", savedIds)
          .gte("blocked_date", today.toISOString().slice(0, 10))
          .lte("blocked_date", weekOut.toISOString().slice(0, 10));
        const blockedIds = new Set((blocked ?? []).map((b) => b.publisher_id as string));
        if (!cancelled) {
          setSavedCount(savedIds.length);
          setAvailableThisWeek(savedIds.filter((id) => !blockedIds.has(id)).length);
        }
      } else if (!cancelled) {
        setSavedCount(0);
        setAvailableThisWeek(0);
      }

      // ── Recommended publishers ─────────────────────────────────────
      // Based on categories/provinces this business has actually
      // requested before — not a guess, just "more like the ones you've
      // already gone for." Falls back to top trust-score publishers
      // overall for a business with no history yet.
      const requestedPublisherIds = Array.from(new Set([
        ...requests.map((r) => r.publisher_id),
        ...channelRequests.map((r) => r.creator_id),
      ].filter(Boolean)));

      let categories: string[] = [];
      let provinces: string[] = [];
      if (requestedPublisherIds.length > 0) {
        const { data: reqPubs } = await supabase.from("publishers").select("category, province").in("id", requestedPublisherIds);
        categories = Array.from(new Set((reqPubs ?? []).map((p) => p.category).filter(Boolean)));
        provinces = Array.from(new Set((reqPubs ?? []).map((p) => p.province).filter(Boolean)));
      }

      let recQuery = supabase.from("publishers").select("*").eq("status", "approved").order("trust_score", { ascending: false }).limit(6);
      if (categories.length > 0) recQuery = recQuery.in("category", categories);
      const { data: recData } = await recQuery;
      let recs = ((recData ?? []) as Publisher[]).filter((p) => !requestedPublisherIds.includes(p.id));
      if (recs.length === 0 && provinces.length > 0) {
        const { data: byProvince } = await supabase.from("publishers").select("*").eq("status", "approved").in("province", provinces).order("trust_score", { ascending: false }).limit(6);
        recs = ((byProvince ?? []) as Publisher[]).filter((p) => !requestedPublisherIds.includes(p.id));
      }
      if (!cancelled) setRecommended(recs.slice(0, 3));

      // ── New publishers matching your saved searches ────────────────
      // Real notifications generated by trg_notify_saved_search_matches
      // (schema_phase33) — not recomputed here, just read back.
      const { data: notifs } = await supabase
        .from("notifications")
        .select("id, title, body")
        .eq("recipient_id", profile!.id)
        .eq("type", "saved_search_match")
        .order("created_at", { ascending: false })
        .limit(3);
      if (!cancelled) setSearchMatches((notifs ?? []) as SearchMatch[]);

      // ── Recent activity ─────────────────────────────────────────────
      const { data: views } = await supabase
        .from("publisher_profile_views")
        .select("publisher_id, created_at, publisher:publishers(name)")
        .eq("viewer_id", profile!.id)
        .order("created_at", { ascending: false })
        .limit(5);
      if (!cancelled) {
        setRecentViews(((views ?? []) as unknown as { publisher_id: string; created_at: string; publisher: { name: string } | null }[])
          .filter((v) => v.publisher)
          .map((v) => ({ publisher_id: v.publisher_id, name: v.publisher!.name, created_at: v.created_at })));
      }

      if (!cancelled) setLoading(false);
    }

    load();
    return () => { cancelled = true; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [profile?.id]);

  // ── Continue your campaign ──────────────────────────────────────────
  const ongoingRequest = [...requests]
    .filter((r) => r.status === "pending" || r.status === "contacted" || r.status === "confirmed")
    .sort((a, b) => b.created_at.localeCompare(a.created_at))[0];
  const ongoingChannelRequest = [...channelRequests]
    .filter((r) => !["completed", "declined", "cancelled", "expired"].includes(r.status))
    .sort((a, b) => b.created_at.localeCompare(a.created_at))[0];

  // ── Recommended next action ──────────────────────────────────────────
  const checklist = profile ? computeBusinessChecklist(profile, requests, channelRequests) : [];
  const nextAction = checklist.find((i) => !i.done);

  if (!profile) return null;

  return (
    <div className="mb-10">
      <h1 className="text-3xl md:text-4xl mb-2">
        {greeting()}{profile.full_name ? `, ${profile.full_name.split(" ")[0]}` : ""}.
      </h1>
      <p className="text-billboard-inkSoft mb-8">
        {loading
          ? "Loading your dashboard…"
          : savedCount === 0
          ? "Save a few publishers to start tracking their availability here."
          : `You have ${availableThisWeek ?? 0} saved publisher${availableThisWeek === 1 ? "" : "s"} available this week.`}
      </p>

      <div className="grid md:grid-cols-2 gap-5 mb-5">
        {/* Recommended publishers */}
        <div className="border-[3px] border-billboard-ink rounded p-5">
          <h2 className="font-bold text-sm mb-3">Recommended publishers</h2>
          {recommended.length === 0 ? (
            <p className="text-sm text-billboard-inkSoft">
              {loading ? "Loading…" : "Browse a few publishers and we'll start recommending similar ones."}
            </p>
          ) : (
            <div className="space-y-2.5">
              {recommended.map((p) => (
                <Link key={p.id} to={`/browse/${p.id}`} className="flex items-center justify-between text-sm hover:text-billboard-greenDeep">
                  <span className="font-semibold">{p.name}</span>
                  <span className="text-billboard-inkSoft font-mono text-xs">{p.city}</span>
                </Link>
              ))}
            </div>
          )}
        </div>

        {/* Continue your campaign */}
        <div className="border-[3px] border-billboard-ink rounded p-5">
          <h2 className="font-bold text-sm mb-3">Continue your campaign</h2>
          {ongoingRequest ? (
            <div>
              <p className="text-sm font-semibold mb-1">{ongoingRequest.publisher?.name ?? "A publisher"}</p>
              <p className="text-xs text-billboard-inkSoft mb-3">Status: {ongoingRequest.status}</p>
              <a href="#your-requests" className="text-xs font-semibold underline">View request →</a>
            </div>
          ) : ongoingChannelRequest ? (
            <div>
              <p className="text-sm font-semibold mb-1">{ongoingChannelRequest.creator?.name ?? "A publisher"}</p>
              <p className="text-xs text-billboard-inkSoft mb-3">Status: {ongoingChannelRequest.status}</p>
              <a href="#your-requests" className="text-xs font-semibold underline">View request →</a>
            </div>
          ) : (
            <div>
              <p className="text-sm text-billboard-inkSoft mb-3">No campaign in progress right now.</p>
              <Link to="/browse" className="text-xs font-semibold underline">Browse publishers →</Link>
            </div>
          )}
          <Link to="/business/publishers" className="block mt-3 text-xs font-semibold underline">Publishers you've worked with →</Link>
          <Link to="/business/opportunities" className="block mt-1 text-xs font-semibold underline">Post what you need, let publishers apply →</Link>
        </div>

        {/* New publishers matching your searches */}
        <div className="border-[3px] border-billboard-ink rounded p-5">
          <h2 className="font-bold text-sm mb-3">New publishers matching your searches</h2>
          {searchMatches.length === 0 ? (
            <p className="text-sm text-billboard-inkSoft">
              {loading ? "Loading…" : <>No new matches yet — <Link to="/saved-searches" className="underline">save a search</Link> to get notified.</>}
            </p>
          ) : (
            <div className="space-y-3">
              {searchMatches.map((n) => (
                <div key={n.id}>
                  <p className="text-sm font-semibold">{n.title}</p>
                  <p className="text-xs text-billboard-inkSoft">{n.body}</p>
                </div>
              ))}
              <Link to="/saved-searches" className="text-xs font-semibold underline">View saved searches →</Link>
            </div>
          )}
        </div>

        {/* Your recent activity */}
        <div className="border-[3px] border-billboard-ink rounded p-5">
          <h2 className="font-bold text-sm mb-3">Your recent activity</h2>
          {recentViews.length === 0 ? (
            <p className="text-sm text-billboard-inkSoft">{loading ? "Loading…" : "Publishers you view will show up here."}</p>
          ) : (
            <div className="space-y-2">
              {recentViews.map((v) => (
                <Link key={`${v.publisher_id}-${v.created_at}`} to={`/browse/${v.publisher_id}`} className="flex items-center justify-between text-sm hover:text-billboard-greenDeep">
                  <span className="font-semibold">{v.name}</span>
                  <span className="text-billboard-inkSoft font-mono text-[10px]">{new Date(v.created_at).toLocaleDateString("en-ZA")}</span>
                </Link>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Recommended next action */}
      {nextAction && (
        <div className="border-[3px] border-billboard-ink rounded p-5 bg-billboard-yellow">
          <h2 className="font-mono text-xs font-semibold uppercase tracking-wide mb-1.5">Recommended next action</h2>
          <p className="font-bold mb-1">{nextAction.label}</p>
          <p className="text-sm text-billboard-inkSoft mb-3">{nextAction.hint}</p>
          {nextAction.actionTo && (
            <Button to={nextAction.actionTo}>
              {nextAction.actionLabel ?? "Do this now"} →
            </Button>
          )}
        </div>
      )}
    </div>
  );
}
