import type { ChannelSlug } from "./channelTypes";
import type { FlagReason } from "./messageSafety";

export type Platform = "Facebook Page" | "Facebook Group" | "Instagram" | "TikTok" | "WhatsApp Channel" | "X" | "LinkedIn" | "YouTube";

export interface PublisherRateCard {
  id: string;
  publisher_id: string;
  label: string;
  price: number;
  description: string | null;
  sort_order: number;
  created_at: string;
}

export interface Publisher {
  id: string;
  name: string;
  city: string;
  province: string;
  // A free-text neighbourhood/area, shown and filterable alongside
  // city/province. Optional — not every publisher sets one, and the
  // suburb autocomplete (SA_SUBURBS_AUTOCOMPLETE in constants.ts) is just a
  // helper, not a constraint on what can be stored here.
  suburb: string | null;
  category: string;
  platforms: Platform[];
  // Social media creators only — which post formats they offer (Story,
  // Feed post, Short-form video, Dedicated video, Carousel, Bio link).
  // null/[] for publishers on other channels, or creators who haven't set
  // this yet.
  placement_types: string[] | null;
  // The 4 request-flow channels only (website, radio, influencer, podcast) —
  // which of that channel's advertisingMethods (see channelTypes.ts) this
  // creator has agreed to offer. null/[] = not set yet, so every format the
  // channel defines is treated as available.
  accepted_ad_formats: string[] | null;
  followers: number;
  engagement: number; // percent
  price_per_post: number; // Rand
  rating: number | null; // null = not enough reviews yet
  reviews: number;
  verified: boolean;
  bio: string;
  audience: string;
  initials: string;
  swatch: string; // tailwind gradient classes for the cover block
  created_at?: string;
  // Phase 5 — self-serve applications, trust & verification
  user_id: string | null; // null = added by hand via /admin, not self-serve
  email: string | null;
  mobile_number: string | null;
  monthly_reach: number | null;
  languages: string[];
  account_age_months: number | null;
  posting_frequency: string | null;
  business_name: string | null;
  company_registration: string | null;
  vat_number: string | null;
  status: PublisherStatus;
  level: PublisherLevel | null;
  trust_score: number;
  publisher_score: number;
  // Response-time badge — a public aggregate only, recomputed server-side
  // by update_publisher_response_stats() whenever a channel_requests
  // campaign this creator owns gets responded to. avg_response_hours is
  // null until they have at least one response on record.
  avg_response_hours: number | null;
  response_count: number;
  // Phase 31 — a coarse "last active" trust signal (see lastActive.ts).
  // Null for admin-added publishers with no user_id, or anyone who has
  // never logged in — the UI omits the badge entirely rather than
  // guessing.
  last_active_at: string | null;
  // Generated by summarize-publisher-audience from real connected-platform
  // follower counts — null until at least one platform's been connected
  // and the publisher's generated a summary. Never invented, never shown
  // without imported data behind it.
  ai_audience_summary: string | null;
  ai_audience_summary_generated_at: string | null;
  email_verified: boolean;
  phone_verified: boolean;
  identity_verified: boolean;
  admin_notes: string | null;
  // Fraud/authenticity — set only by an admin-triggered AI second opinion
  // (publisher-authenticity-check edge function). Null until an admin runs
  // one; see authenticitySignals.ts for the separate, always-on rule-based
  // signals that don't depend on this.
  authenticity_risk: "low" | "medium" | "high" | null;
  authenticity_notes: string | null;
  authenticity_checked_at: string | null;
  // Video/portfolio (schema_phase27_portfolio.sql) — intro_video_url is a
  // link to an existing YouTube/Vimeo/TikTok/Instagram video, never a
  // self-hosted file (see videoEmbed.ts). portfolio_images holds up to 5
  // public Storage URLs, each capped at 3MB by the bucket itself.
  intro_video_url: string | null;
  portfolio_images: string[];
  rejected_reason: string | null;
  featured: boolean;
  featured_until: string | null;
  reviewed_at: string | null;
  // Phase 17 — multi-channel marketplace. Defaults to "social-media" for every
  // row that existed before this column did, so the original directory/PayFast
  // flow keeps working unchanged for every publisher already in the database.
  channel_slug: ChannelSlug;
  // Phase 74 — per-channel structured fields that don't apply across all 12
  // channels (sport/competition/season for sports, foot traffic/till for
  // informal-retail, etc.). Loosely typed here on purpose — see
  // channelOnboardingSchemas.ts's own header for why a shared shape across
  // contrasting channels would be wrong, and for the typed accessors
  // (getSportsMetadata() etc.) that give real typing at the point of use.
  // Was already a real jsonb column in the database; only just added here —
  // every use of it before this line went through an untyped cast.
  channel_metadata: Record<string, unknown> | null;
}

export type PublisherStatus = "pending_review" | "approved" | "rejected" | "suspended";
export type PublisherLevel = "rising" | "verified" | "premium" | "elite";

export interface Category {
  slug: string;
  name: string;
  icon: "food" | "fitness" | "beauty" | "home" | "family" | "auto" | "fashion" | "tech"
    | "lifestyle" | "news" | "community" | "retail" | "property" | "pets" | "events" | "social";
}

export type UserRole = "business" | "admin" | "publisher";

export type ContentStudioSubscriptionStatus = "pending" | "active" | "past_due" | "cancelled";

export interface ContentStudioSubscription {
  id: string;
  business_id: string;
  status: ContentStudioSubscriptionStatus;
  current_period_end: string | null;
  created_at: string;
}

export interface Notification {
  id: string;
  recipient_id: string;
  type: string;
  title: string;
  body: string;
  link: string | null;
  read_at: string | null;
  created_at: string;
}

export type ReportReason = "fake_followers" | "no_response" | "inappropriate_content" | "scam_or_fraud" | "other";
export type ReportStatus = "open" | "reviewed" | "dismissed";

export interface Report {
  id: string;
  reporter_id: string;
  publisher_id: string;
  reason: ReportReason;
  details: string | null;
  status: ReportStatus;
  admin_notes: string | null;
  created_at: string;
  reviewed_at: string | null;
  publisher?: Pick<Publisher, "name"> | null;
}

export type DisputeCategory = "payment_issue" | "quality_issue" | "non_delivery" | "communication" | "other";
export type DisputeStatus = "open" | "awaiting_response" | "resolved" | "closed";
export type DisputeOutcome = "refund_business" | "release_to_publisher" | "partial" | "no_action" | "other";
export type DisputeSenderRole = "business" | "publisher" | "admin";

export interface DisputeMessage {
  id: string;
  dispute_id: string;
  sender_id: string;
  sender_role: DisputeSenderRole;
  body: string;
  created_at: string;
}

export interface Dispute {
  id: string;
  request_id: string | null;
  channel_request_id: string | null;
  business_id: string;
  publisher_id: string;
  opened_by_role: "business" | "publisher";
  category: DisputeCategory;
  subject: string;
  status: DisputeStatus;
  resolution_outcome: DisputeOutcome | null;
  resolution_notes: string | null;
  created_at: string;
  updated_at: string;
  closed_at: string | null;
  publisher?: Pick<Publisher, "name"> | null;
  business?: Pick<Profile, "full_name" | "company_name"> | null;
  dispute_messages?: DisputeMessage[];
}

export interface Profile {
  id: string;
  role: UserRole;
  full_name: string | null;
  company_name: string | null;
  phone: string | null;
  created_at: string;
  // Phase 7 — business verification
  province: string | null;
  city: string | null;
  industry: string | null;
  website: string | null;
  facebook_url: string | null;
  instagram_url: string | null;
  email_verified: boolean;
  phone_verified: boolean;
  business_verified: boolean;
}

export type RequestStatus = "pending" | "contacted" | "confirmed" | "declined" | "completed";
export type PaymentStatus = "pending" | "paid" | "failed" | "cancelled";
export type PayoutStatus = "unpaid" | "paid";

export type PaymentMethod = "payfast" | "eft";

export interface Payment {
  id: string;
  request_id: string;
  business_id: string;
  amount: number;
  status: PaymentStatus;
  payfast_payment_id: string | null;
  payout_status: PayoutStatus;
  payout_date: string | null;
  created_at: string;
  paid_at: string | null;
  method: PaymentMethod;
  eft_reference: string | null;
  eft_confirmed_by_business_at: string | null;
}

export type ReviewAuthorRole = "business" | "publisher";

export interface Review {
  id: string;
  request_id: string;
  publisher_id: string;
  business_id: string;
  rating: number;
  comment: string | null;
  created_at: string;
  author_role: ReviewAuthorRole;
  communication_rating: number | null;
  professionalism_rating: number | null;
  quality_rating: number | null;
  timeliness_rating: number | null;
  value_rating: number | null;
  business?: Pick<Profile, "full_name" | "company_name"> | null;
}

export interface PublisherRequest {
  id: string;
  publisher_id: string;
  business_id: string;
  campaign_message: string;
  budget: number | null;
  agreed_amount: number | null;
  status: RequestStatus;
  created_at: string;
  // Phase 60 — set when this booking is part of a managed campaign; see
  // schema_phase60_agency_campaigns.sql. Only ever meaningful to the
  // business themselves — resolving it to a campaign name goes through
  // get_my_managed_campaigns() (schema_phase61), not a raw join here.
  agency_campaign_id: string | null;
  // present when fetched with a join
  publisher?: Pick<Publisher, "id" | "name" | "city" | "province"> | null;
  business?: Pick<Profile, "full_name" | "company_name" | "phone" | "email_verified" | "phone_verified" | "business_verified"> | null;
  payments?: Payment[];
  reviews?: Review[];
}

export type SenderRole = "business" | "admin" | "publisher";

export interface Message {
  id: string;
  request_id: string | null;
  channel_request_id: string | null; // Phase 56 — mutually exclusive with request_id, see schema_phase56_channel_messaging.sql
  sender_id: string;
  sender_role: SenderRole;
  body: string;
  created_at: string;
  read_at: string | null;
  flagged: boolean; // Phase 57 — see schema_phase57_message_safety.sql
  flag_reason: FlagReason | null;
  flagged_at: string | null;
}

export interface ContactMessage {
  id: string;
  name: string;
  email: string;
  message: string;
  created_at: string;
}

export type CareerApplicationStatus = "new" | "reviewing" | "interview" | "offer" | "hired" | "rejected";

export interface CareerApplication {
  id: string;
  name: string;
  email: string;
  role: string;
  cv_path: string;
  cv_filename: string;
  portfolio_url: string | null;
  linkedin_url: string | null;
  location: string;
  cover_letter: string;
  status: CareerApplicationStatus;
  interview_date: string | null;
  admin_notes: string | null;
  created_at: string;
  reviewed_at: string | null;
}

export type WorkWithUsCategory =
  | "developers" | "designers" | "sales" | "marketing" | "creators"
  | "community_managers" | "sales_representatives" | "freelancers" | "internships";

export type WorkWithUsStatus = "new" | "contacted" | "archived";

export interface WorkWithUsApplication {
  id: string;
  name: string;
  email: string;
  category: WorkWithUsCategory;
  location: string;
  message: string;
  portfolio_url: string | null;
  linkedin_url: string | null;
  attachment_path: string | null;
  attachment_filename: string | null;
  status: WorkWithUsStatus;
  admin_notes: string | null;
  created_at: string;
  reviewed_at: string | null;
}

export type PartnerCategory =
  | "marketing_agencies" | "web_developers" | "pr_agencies" | "photographers"
  | "event_companies" | "payment_providers" | "software_companies"
  | "creator_networks" | "media_organisations" | "business_associations";

export type PartnerStatus = "new" | "contacted" | "in_discussion" | "active" | "declined";

export type PartnerType = "agency" | "technology" | "media" | "community" | "referral";

export interface PartnerApplication {
  id: string;
  company_name: string;
  contact_name: string;
  email: string;
  phone: string | null;
  category: PartnerCategory | null;
  partner_type: PartnerType | null;
  website: string | null;
  message: string;
  status: PartnerStatus;
  admin_notes: string | null;
  created_at: string;
  reviewed_at: string | null;
}

export type AdvertiseProduct =
  | "website_advertising" | "newsletter_sponsorship" | "featured_placement"
  | "sponsored_article" | "brand_partnership";

export type AdvertiseStatus = "new" | "contacted" | "in_discussion" | "active" | "declined";

export interface AdvertiseInquiry {
  id: string;
  company_name: string;
  contact_name: string;
  email: string;
  phone: string | null;
  product: AdvertiseProduct;
  budget_range: string | null;
  message: string;
  status: AdvertiseStatus;
  admin_notes: string | null;
  created_at: string;
  reviewed_at: string | null;
}

export interface CommunityAnnouncement {
  id: string;
  title: string;
  body: string;
  pinned: boolean;
  is_published: boolean;
  created_at: string;
  updated_at: string;
}

export type CommunityEventType = "webinar" | "in_person" | "online";

export interface CommunityEvent {
  id: string;
  title: string;
  description: string;
  event_type: CommunityEventType;
  starts_at: string;
  ends_at: string | null;
  location_or_link: string;
  is_published: boolean;
  created_at: string;
  updated_at: string;
}

export type CommunityQuestionCategory = "publisher" | "business" | "marketing";
export type CommunityQuestionStatus = "pending" | "answered" | "published";

export interface CommunityQuestion {
  id: string;
  category: CommunityQuestionCategory;
  question: string;
  asked_by_name: string | null;
  asked_by_email: string | null;
  answer: string | null;
  status: CommunityQuestionStatus;
  admin_notes: string | null;
  created_at: string;
  answered_at: string | null;
}

export interface Conversation {
  id: string;
  business_id: string;
  publisher_id: string;
  last_message_at: string;
  last_message_preview: string | null;
  created_at: string;
  publisher?: Pick<Publisher, "id" | "name" | "initials" | "city" | "province" | "swatch"> | null;
  business?: Pick<Profile, "full_name" | "company_name"> | null;
}

export interface ConversationMessage {
  id: string;
  conversation_id: string;
  sender_id: string;
  sender_role: SenderRole;
  body: string;
  created_at: string;
  read_at: string | null;
  flagged: boolean; // Phase 57 — see schema_phase57_message_safety.sql
  flag_reason: FlagReason | null;
  flagged_at: string | null;
}

// ─── Phase 17 — Channel request workflow (influencer / website / podcast / radio) ──
//
// A parallel, deliberately separate request model for the four "request only,
// no online checkout" channels. Kept apart from PublisherRequest/Payment (the
// PayFast-backed social-media flow) rather than merged into it, since the
// payment mechanics genuinely differ — see /areas escrow note in the schema
// migration for the full state machine this type mirrors.
export type ChannelRequestStatus =
  | "pending"            // awaiting the creator's approve/decline/counter (7-day window)
  | "countered"          // creator proposed a different price; awaiting the business's response
  | "declined"           // creator declined, or an admin closed it as unresponsive
  | "cancelled"          // business withdrew, or declined a counter, or an admin closed it unpaid/unresponsive
  | "awaiting_payment"   // creator approved (or business accepted a counter); business must pay within 7 days
  | "payment_submitted"  // business self-reported payment; awaiting confirmation
  | "paid"               // platform confirmed funds received — post can now go live
  | "live"               // sponsored content is live; creator payout due within 48h
  | "completed";         // creator payout sent

export type CampaignStatus = "active" | "paused" | "archived";
export type CampaignEventType = "click" | "visit" | "lead" | "conversion";

export interface Campaign {
  id: string;
  owner_id: string;
  request_id: string | null;
  channel_request_id: string | null;
  name: string;
  slug: string;
  destination_url: string;
  utm_source: string;
  utm_medium: string;
  utm_campaign: string;
  utm_content: string | null;
  status: CampaignStatus;
  created_at: string;
}

export interface CampaignStats {
  campaign_id: string;
  owner_id: string;
  slug: string;
  name: string;
  status: CampaignStatus;
  clicks: number;
  visits: number;
  leads: number;
  conversions: number;
  conversion_value: number;
  last_event_at: string | null;
}

export interface SavedSearch {
  id: string;
  business_id: string;
  name: string;
  // Same shape as browseFilters.ts's Filters — stored as jsonb so a new
  // filter field later doesn't need a migration. See
  // schema_phase33_saved_searches.sql for which fields the alert-matching
  // trigger actually reads (the structured subset only, not the fuzzy
  // keyword/age/gender fields).
  filters: Record<string, unknown>;
  alerts_enabled: boolean;
  last_alerted_at: string | null;
  created_at: string;
}

export interface ChannelRequest {
  id: string;
  channel_slug: ChannelSlug;
  creator_id: string;
  business_id: string;
  campaign_message: string;
  advertising_method: string;
  proposed_amount: number;
  status: ChannelRequestStatus;
  created_at: string;
  approval_due_at: string;
  responded_at: string | null;
  // Set only while/after status is 'countered' — see schema_phase35.
  // Once a counter is accepted, proposed_amount above is overwritten with
  // this value, so these three stay as a historical record of what was
  // countered rather than something else needs to keep reading.
  counter_amount: number | null;
  counter_note: string | null;
  countered_at: string | null;
  payment_due_at: string | null;
  payment_submitted_at: string | null;
  paid_at: string | null;
  live_at: string | null;
  payout_due_at: string | null;
  completed_at: string | null;
  // Phase 54 — "Campaign duration: 7 days" style spec, business-set.
  duration_days: number | null;
  // Phase 60 — see the same field on PublisherRequest above.
  agency_campaign_id: string | null;
  // present when fetched with a join
  creator?: Pick<Publisher, "id" | "name" | "city" | "province" | "channel_slug"> | null;
  business?: Pick<Profile, "full_name" | "company_name" | "phone"> | null;
}

// ─── Phase 53 — Content approval (business brief → creator draft → approve/publish) ──
//
// Gates channel_requests' paid -> live transition: a placement can't go
// live until its content_approvals row reaches 'approved' (or 'published').
// See schema_phase53_content_approval.sql for the full state machine.
export type ContentApprovalStatus =
  | "awaiting_draft"    // business submitted the brief; creator hasn't drafted yet
  | "awaiting_review"   // creator submitted a draft; business must decide
  | "changes_requested" // business asked for changes; creator must revise
  | "approved"          // business approved; creator may publish
  | "published";        // creator published — channel_requests can now move to 'live'

export interface ContentApproval {
  id: string;
  channel_request_id: string;
  status: ContentApprovalStatus;
  brief_image_path: string | null;
  brief_video_path: string | null;
  brief_caption: string | null;
  brief_cta_label: string | null;
  brief_link: string | null;
  submitted_at: string;
  draft_image_path: string | null;
  draft_video_path: string | null;
  draft_caption: string | null;
  draft_notes: string | null;
  draft_submitted_at: string | null;
  change_request_notes: string | null;
  reviewed_at: string | null;
  approved_at: string | null;
  published_at: string | null;
}

// ─── Phase 54 — Structured deliverables ────────────────────────────────
// One row per promised line item ("1 Instagram Reel", "1 promo code"),
// each independently tracked through its own 5-state lifecycle. See
// schema_phase54_deliverables.sql for the full state machine — exactly
// these 5 states, no more.
export type DeliverableStatus = "pending" | "submitted" | "approved" | "published" | "verified";

export interface Deliverable {
  id: string;
  channel_request_id: string | null;
  request_id: string | null;
  label: string;
  quantity: number;
  notes: string | null;
  sort_order: number;
  status: DeliverableStatus;
  submission_url: string | null;
  submission_notes: string | null;
  submitted_at: string | null;
  business_notes: string | null;
  approved_at: string | null;
  published_at: string | null;
  verified_at: string | null;
  verified_by: string | null;
  created_at: string;
}

// ─── Phase 59 — Agency Core, part 1: leads + client CRM ────────────────
// Admin-only, both tables — see schema_phase59_agency_crm.sql. No
// business/publisher-facing type ever reads these.

export type AgencyLeadStage = "new" | "contacted" | "qualified" | "proposal" | "won" | "lost" | "campaign" | "renewal";

export interface AgencyLead {
  id: string;
  business_name: string;
  contact_name: string | null;
  contact_email: string | null;
  contact_phone: string | null;
  business_id: string | null;
  stage: AgencyLeadStage;
  source: string | null;
  estimated_value: number | null;
  // Expected to be an admin account — see schema_phase59's note on why
  // this isn't a new profiles.role.
  campaign_manager_id: string | null;
  notes: string | null;
  next_action: string | null;
  next_action_due: string | null;
  created_at: string;
  updated_at: string;
  campaign_manager?: Pick<Profile, "full_name"> | null;
}

export type AgencyServiceLevel = "self_service" | "assisted" | "managed";
export type AgencyRenewalStatus = "none" | "upcoming" | "due" | "overdue" | "renewed";

export interface AgencyClient {
  id: string;
  business_id: string;
  service_level: AgencyServiceLevel;
  campaign_manager_id: string | null;
  lead_id: string | null;
  renewal_status: AgencyRenewalStatus;
  notes: string | null;
  created_at: string;
  updated_at: string;
  business?: Pick<Profile, "full_name" | "company_name" | "phone"> | null;
  campaign_manager?: Pick<Profile, "full_name"> | null;
}

// Return shape of agency_client_totals(business_id) — see
// schema_phase59_agency_crm.sql.
export interface AgencyClientTotals {
  lifetime_spend: number;
  campaign_count: number;
  last_campaign_at: string | null;
}

// ─── Phase 60 — Agency Core, part 2: the managed-campaign entity ───────
// Admin-only, same as agency_leads/agency_clients. Deliberately coarse
// status — see schema_phase60_agency_campaigns.sql's header for why the
// brief's Creative/Approval/Publication/Proof/Tracking stages collapse
// into "in_progress" here rather than being duplicated: that detail
// already lives on whichever requests/channel_requests end up linked via
// agency_campaign_id.
export type AgencyCampaignStatus = "draft" | "proposed" | "payment_pending" | "planning" | "in_progress" | "reporting" | "completed" | "cancelled";

export interface AgencyCampaign {
  id: string;
  client_id: string;
  campaign_manager_id: string | null;
  name: string;
  objective: string | null;
  brief: string | null;
  target_audience: string | null;
  budget: number | null;
  start_date: string | null;
  end_date: string | null;
  status: AgencyCampaignStatus;
  created_at: string;
  updated_at: string;
  // Phase 65 — pay ChatSched once for the whole campaign instead of per
  // linked booking. package_price null means no package: itemized, as
  // before. See schema_phase65_campaign_packages.sql.
  package_price: number | null;
  package_payment_status: "unpaid" | "payment_submitted" | "paid";
  package_payment_reference: string | null;
  package_payment_submitted_at: string | null;
  package_paid_at: string | null;
}

// Return shape of agency_campaign_totals(campaign_id) — see
// schema_phase60_agency_campaigns.sql.
export interface AgencyCampaignTotals {
  linked_requests: number;
  paid_requests: number;
  total_spend: number;
}

// The subset of an existing requests/channel_requests row this phase
// needs to show in the "link to this campaign" picker — not the full
// Request/ChannelRequest shape, since all that's needed here is enough
// to identify and link one.
export interface LinkableRequest {
  id: string;
  kind: "request" | "channel_request";
  label: string;
  agency_campaign_id: string | null;
}

// ─── Phase 67 — Relationship history ────────────────────────────────────
// Return shapes of my_publisher_relationships() / my_business_relationships()
// — see schema_phase67_relationship_history.sql. Self-scoped, not
// admin-only — a business/publisher reading their own paid history.

export interface PublisherRelationship {
  publisher_id: string;
  publisher_name: string;
  channel_slug: ChannelSlug;
  city: string;
  province: string;
  campaign_count: number;
  total_spent: number;
  last_campaign_at: string | null;
  avg_rating: number | null;
}

export interface BusinessRelationship {
  business_id: string;
  business_name: string;
  campaign_count: number;
  total_earned: number;
  last_campaign_at: string | null;
}

// ─── Phase 61 — client-facing managed-campaign view ────────────────────
// Return shapes of the get_my_managed_campaign* RPCs
// (schema_phase61_managed_campaign_client_view.sql) — narrower,
// business-safe projections of AgencyCampaign/AgencyCampaignTotals
// above, not the same interfaces reused, since the RPCs deliberately
// return a different (smaller, resolved-name-instead-of-id) shape than
// the admin-only table/function they're modeled on.
export interface MyManagedCampaign {
  id: string;
  name: string;
  objective: string | null;
  brief: string | null;
  target_audience: string | null;
  budget: number | null;
  start_date: string | null;
  end_date: string | null;
  status: AgencyCampaignStatus;
  campaign_manager_name: string | null;
  created_at: string;
  // Phase 65 — see AgencyCampaign above; same fields, same meaning.
  package_price: number | null;
  package_payment_status: "unpaid" | "payment_submitted" | "paid";
  package_payment_reference: string | null;
  package_paid_at: string | null;
}

export interface MyManagedCampaignBooking {
  id: string;
  kind: "request" | "channel_request";
  status: string;
  amount: number | null;
  created_at: string;
}

// ─── Phase 15 — admin audit log (schema_phase15_audit_log.sql) ─────────
// First frontend type for this table — it's existed since Phase 15 with
// no viewer. admin_id null means system-originated (see
// schema_phase62_agency_campaign_auto_advance.sql and
// supabase/functions/verify-otp/index.ts, the two places that already
// write null on purpose) rather than a specific admin's action.
export interface AdminAuditLogEntry {
  id: string;
  admin_id: string | null;
  action: string;
  target_table: string;
  target_id: string | null;
  detail: Record<string, unknown> | null;
  created_at: string;
}

// ─── Phase 68 — opportunity feed / reverse marketplace (schema_phase68_opportunity_marketplace.sql) ──
export type OpportunityStatus = "open" | "filled" | "closed" | "cancelled";
export type OpportunityApplicationStatus = "pending" | "accepted" | "declined" | "withdrawn";

export interface Opportunity {
  id: string;
  business_id: string;
  title: string;
  brief: string;
  channel_slug: ChannelSlug | null;
  budget_min: number | null;
  budget_max: number | null;
  // How many applicants this needs — not how many have accepted so far,
  // which is a live count against OpportunityApplication rows. See
  // schema_phase69_opportunity_multi_accept.sql.
  publishers_needed: number;
  status: OpportunityStatus;
  expires_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface OpportunityApplication {
  id: string;
  opportunity_id: string;
  publisher_id: string;
  message: string;
  advertising_method: string | null;
  proposed_amount: number | null;
  status: OpportunityApplicationStatus;
  created_at: string;
  updated_at: string;
}

