import type { Publisher } from "../lib/types";

// A complete, valid Publisher with sensible defaults — pass overrides for
// whatever a given test actually cares about instead of repeating every
// field in every test file.
export function makePublisher(overrides: Partial<Publisher> = {}): Publisher {
  return {
    id: "pub-1",
    name: "Test Publisher",
    city: "Cape Town",
    province: "Western Cape",
    suburb: null,
    category: "Food & Drink",
    platforms: ["Facebook Page"],
    placement_types: null,
    accepted_ad_formats: null,
    channel_metadata: null,
    authenticity_risk: null,
    authenticity_notes: null,
    authenticity_checked_at: null,
    intro_video_url: null,
    portfolio_images: [],
    followers: 5000,
    engagement: 4.5,
    price_per_post: 150,
    rating: null,
    reviews: 0,
    verified: false,
    bio: "A test publisher for unit tests.",
    audience: "25-44, local residents",
    initials: "TP",
    swatch: "from-billboard-yellow to-billboard-red",
    created_at: "2026-01-01T00:00:00.000Z",
    user_id: "user-1",
    email: "publisher@example.com",
    mobile_number: null,
    monthly_reach: null,
    languages: ["English"],
    account_age_months: 12,
    posting_frequency: "weekly",
    business_name: null,
    company_registration: null,
    vat_number: null,
    status: "approved",
    level: "rising",
    trust_score: 50,
    publisher_score: 50,
    avg_response_hours: null,
    response_count: 0,
    last_active_at: null,
    ai_audience_summary: null,
    ai_audience_summary_generated_at: null,
    email_verified: true,
    phone_verified: false,
    identity_verified: false,
    admin_notes: null,
    rejected_reason: null,
    featured: false,
    featured_until: null,
    reviewed_at: "2026-01-02T00:00:00.000Z",
    channel_slug: "social-media",
    ...overrides,
  };
}
